name: Publish docsite

on:
  push:
    branches:
      - 'stop-gap-v2'

jobs:
  publish:
    name: Publish Temp Docsite
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.5'
    - uses: actions/setup-node@v2
      with:
        node-version: '10' #Todo figure out what version it should use
    - name: Build docsite
      run: sh ./.github/actions/build-docsite/script.sh
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2
    - name: Create Bucket Name
      id: create_name
      run: |
        BUCKET_NAME=stop-gap
        echo $BUCKET_NAME
        echo "::set-output name=bucket_name::$BUCKET_NAME"
    - name: Sync zip to Bucket
      run: |
        aws s3 sync ./_book/ s3://$BUCKET_NAME --acl public-read
      env:
        BUCKET_NAME: ${{ steps.create_name.outputs.bucket_name }}
